# Generated by Django 2.2.1 on 2019-05-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('facility', models.TextField(default='none')),
                ('price_per_person', models.TextField(default='none')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.City')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.bmp', upload_to='hotel_pics')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('no_of_people', models.CharField(max_length=3)),
                ('date_of_booking', models.DateField()),
                ('time_of_booking', models.TimeField()),
                ('client_email', models.EmailField(max_length=254)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.bmp', upload_to='city_pics')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.City')),
            ],
        ),
    ]
