# Generated by Django 2.2.1 on 2019-05-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryPic',
        ),
    ]
