# Generated by Django 2.2.1 on 2019-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190525_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypic',
            name='image',
            field=models.ImageField(default='default.bmp', upload_to='gallery_pics'),
        ),
    ]
