# Generated by Django 2.2.2 on 2019-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='nonveg_description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nonveg_price',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='veg_nonveg_key',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='veg_price',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
