# Generated by Django 2.2.2 on 2019-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_hotel_veg_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='veg_nonveg_key',
            field=models.CharField(default='none', max_length=1),
        ),
    ]
