# Generated by Django 2.2.2 on 2019-06-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190626_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='default.bmp', upload_to='hotel_pics'),
        ),
    ]
