# Generated by Django 2.2.2 on 2019-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190627_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='none', max_length=100)),
                ('phone_no', models.CharField(default='none', max_length=15)),
                ('no_of_people', models.CharField(default='none', max_length=3)),
                ('date_of_booking', models.CharField(default='none', max_length=100)),
                ('theme', models.CharField(default='none', max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequestregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='time_of_booking',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
