# Generated by Django 2.2.2 on 2019-09-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190912_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientRequestBooking',
            new_name='ClientBookingRequest',
        ),
        migrations.RenameModel(
            old_name='ClientRequestregistration',
            new_name='ClientRegistrationRequest',
        ),
    ]
